export const data = [
  {
    name: "aaman",
    customer_name: "aaman",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "abcd",
    customer_name: "abcd",
    customer_group: "Government",
    customer_type: "Individual",
  },
  {
    name: "ABDULLAH HASAN",
    customer_name: "ABDULLAH HASAN",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Ahmad",
    customer_name: "Ahmad",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Ali Farooq",
    customer_name: "Ali Farooq",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Aman",
    customer_name: "Aman",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Ameer Farooq",
    customer_name: "Ameer Farooq",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Ameer Farooq - 1",
    customer_name: "Ameer Farooq",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Ameer Farooq - 2",
    customer_name: "Ameer Farooq",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Amir Farooq",
    customer_name: "Amir Farooq",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "as",
    customer_name: "as",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "asif hussain",
    customer_name: "asif hussain",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "IBRAHIM DASHTI",
    customer_name: "IBRAHIM DASHTI",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "IK",
    customer_name: "PK",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "irfan hussain",
    customer_name: "irfan hussain",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Ishtiyaq  Khan",
    customer_name: "Ishtiyaq  Khan",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Khalid Shekh",
    customer_name: "Khalid Shekh",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "ram",
    customer_name: "amir hussain",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "rashid hussain",
    customer_name: "rashid hussain",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Rauf",
    customer_name: "Rauf",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Sameer Farooq",
    customer_name: "Sameer Farooq",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "saqib hussain",
    customer_name: "saqib hussain",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Sumit",
    customer_name: "Sumit ",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "test",
    customer_name: "test",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test1 test",
    customer_name: "Test1 test",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test123",
    customer_name: "Test123",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test2",
    customer_name: "Test2",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test2 - 1",
    customer_name: "Test2",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test2 - 2",
    customer_name: "Test2",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test2 - 3",
    customer_name: "Test2",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Test45",
    customer_name: "Test45",
    customer_group: "Individual",
    customer_type: "Individual",
  },
  {
    name: "usman khalid",
    customer_name: "usman khalid",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "Yusuff Mohammed",
    customer_name: "Yusuff Mohammed",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "zaid hussain",
    customer_name: "zaid hussain",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
  {
    name: "zara",
    customer_name: "zara",
    customer_group: "All Customer Groups",
    customer_type: "Individual",
  },
];
